"use client";

import { useCallback, useEffect, useState } from "react";

type LeaderboardEntry = {
  userId: string;
  email: string;
  points: number;
};

type LeaderboardResponse = {
  gameweek: {
    id: string;
    number: number;
    name: string | null;
    deadlineAt: string;
  };
  scores: LeaderboardEntry[];
};

export default function LeaderboardPage() {
  const [data, setData] = useState<LeaderboardResponse | null>(
    null
  );
  const [loading, setLoading] = useState(true);
  const [recalculating, setRecalculating] = useState(false);
  const [message, setMessage] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);

  const load = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/gameweeks/leaderboard", {
        credentials: "include"
      });
      if (!res.ok) {
        setData(null);
        setError("Failed to load leaderboard.");
        return;
      }
      const json = (await res.json()) as LeaderboardResponse;
      setData(json);
    } catch {
      setData(null);
      setError("Failed to load leaderboard.");
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  async function handleRunDebugScoring() {
    setRecalculating(true);
    setMessage(null);
    setError(null);
    try {
      const res = await fetch("/api/gameweeks/score-debug", {
        method: "POST",
        credentials: "include"
      });

      const json = await res.json().catch(() => null);

      if (!res.ok) {
        setError(
          json?.error ||
            "Failed to run debug scoring. Check the console or server logs."
        );
      } else {
        setMessage(
          json?.message ||
            "Debug scoring complete. Leaderboard refreshed."
        );
        // Reload leaderboard data
        await load();
      }
    } catch {
      setError("Something went wrong running debug scoring.");
    } finally {
      setRecalculating(false);
    }
  }

  if (loading && !data) {
    return (
      <main className="space-y-6">
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5">
          <p className="text-sm text-slate-300">
            Loading leaderboard...
          </p>
        </section>
      </main>
    );
  }

  if (!data) {
    return (
      <main className="space-y-6">
        <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5">
          <h2 className="text-xl font-semibold mb-2">
            Leaderboard unavailable
          </h2>
          <p className="text-sm text-slate-300 mb-3">
            We couldn&apos;t load the current gameweek leaderboard.
          </p>
          {error && (
            <p className="text-xs text-red-400">{error}</p>
          )}
          <button
            type="button"
            onClick={load}
            className="mt-2 rounded-full bg-emerald-400 px-4 py-2 text-xs font-semibold text-slate-950 hover:bg-emerald-300"
          >
            Retry
          </button>
        </section>
      </main>
    );
  }

  const { gameweek, scores } = data;

  return (
    <main className="space-y-6">
      <section className="rounded-2xl border border-slate-800 bg-slate-900/50 p-5">
        <h2 className="text-xl font-semibold mb-1">
          Gameweek {gameweek.number} Leaderboard
        </h2>
        <p className="text-xs text-slate-400 mb-2">
          This is a debug shell: points are generated by a test scoring
          engine so we can see the full game loop (entries → scores →
          leaderboard) working.
        </p>
        <div className="flex flex-wrap items-center gap-3 text-xs">
          <button
            type="button"
            onClick={handleRunDebugScoring}
            disabled={recalculating}
            className={`rounded-full px-4 py-2 font-semibold transition ${
              recalculating
                ? "bg-slate-700 text-slate-400 cursor-not-allowed"
                : "bg-emerald-400 text-slate-950 hover:bg-emerald-300"
            }`}
          >
            {recalculating
              ? "Running debug scoring..."
              : "Run Debug Scoring"}
          </button>
          {message && (
            <span className="text-emerald-300">{message}</span>
          )}
          {error && (
            <span className="text-red-400">{error}</span>
          )}
        </div>
      </section>

      <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4">
        {scores.length === 0 ? (
          <p className="text-sm text-slate-300">
            No entries yet. Build and lock your squad to appear on the
            leaderboard.
          </p>
        ) : (
          <table className="w-full text-left text-xs">
            <thead className="border-b border-slate-700 text-slate-300">
              <tr>
                <th className="py-2 pr-4">Rank</th>
                <th className="py-2 pr-4">Manager</th>
                <th className="py-2 pr-4 text-right">Points</th>
              </tr>
            </thead>
            <tbody>
              {scores.map((entry, index) => (
                <tr
                  key={entry.userId}
                  className="border-b border-slate-800 last:border-b-0"
                >
                  <td className="py-2 pr-4 text-slate-400">
                    #{index + 1}
                  </td>
                  <td className="py-2 pr-4 text-slate-100">
                    {entry.email}
                  </td>
                  <td className="py-2 pr-4 text-right text-slate-100">
                    {entry.points}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        )}
      </section>
    </main>
  );
}
