// lib/objectives/season1.ts

export const SEASON_CODE = "S1";

export type ObjectiveRequirementType =
  | "OPEN_PACKS_ANY"
  | "SUBMIT_FANTASY_SQUAD"
  | "EARN_FANTASY_POINTS"
  | "PLAY_BATTLES"
  | "WIN_BATTLES"
  | "OWN_MONSTERS_TOTAL"
  | "OWN_MONSTERS_RARE_OR_BETTER"
  | "EVOLVE_MONSTERS"
  | "USE_MARKETPLACE_BUY"
  | "USE_MARKETPLACE_SELL";

type SeasonObjectiveConfig = {
  code: string;
  name: string;
  description: string;
  period: string;
  type: ObjectiveRequirementType | string;
  category?: string;
  seasonCode?: string;
  sortOrder?: number;
  isRepeatable?: boolean;
  targetValue: number;
  rewardType: string;   // "coins" | "pack" | "special"
  rewardValue: string;  // e.g. "500" or "gold"
};

type SeasonObjectiveSetConfig = {
  code: string;
  title: string;
  description: string;
  seasonCode: string;
  sortOrder?: number;
  rewardType: string;   // "coins" | "pack" | "special"
  rewardValue: string;
  objectiveCodes: string[];
};

export const season1Objectives: SeasonObjectiveConfig[] = [
  // Getting Started Path
  {
    code: "GET_STARTED_01",
    name: "First Rip",
    description: "Open your first pack.",
    period: "season",
    type: "OPEN_PACKS_ANY",
    category: "Getting Started",
    seasonCode: SEASON_CODE,
    sortOrder: 1,
    isRepeatable: false,
    targetValue: 1,
    rewardType: "coins",
    rewardValue: "250",
  },
  {
    code: "GET_STARTED_02",
    name: "Squad on Paper",
    description: "Submit a fantasy squad for any gameweek.",
    period: "season",
    type: "SUBMIT_FANTASY_SQUAD",
    category: "Getting Started",
    seasonCode: SEASON_CODE,
    sortOrder: 2,
    isRepeatable: false,
    targetValue: 1,
    rewardType: "coins",
    rewardValue: "250",
  },
  {
    code: "GET_STARTED_03",
    name: "First Battle",
    description: "Play 1 battle against another player.",
    period: "season",
    type: "PLAY_BATTLES",
    category: "Getting Started",
    seasonCode: SEASON_CODE,
    sortOrder: 3,
    isRepeatable: false,
    targetValue: 1,
    rewardType: "coins",
    rewardValue: "400",
  },
  {
    code: "GET_STARTED_04",
    name: "One Step Stronger",
    description: "Evolve any monster once.",
    period: "season",
    type: "EVOLVE_MONSTERS",
    category: "Getting Started",
    seasonCode: SEASON_CODE,
    sortOrder: 4,
    isRepeatable: false,
    targetValue: 1,
    rewardType: "pack",
    rewardValue: "starter",
  },

  // Pack Grinder Path
  {
    code: "PACK_GRINDER_01",
    name: "Pack Fan",
    description: "Open 10 packs total.",
    period: "season",
    type: "OPEN_PACKS_ANY",
    category: "Pack Grinder",
    seasonCode: SEASON_CODE,
    sortOrder: 10,
    isRepeatable: false,
    targetValue: 10,
    rewardType: "coins",
    rewardValue: "500",
  },
  {
    code: "PACK_GRINDER_02",
    name: "Can’t Stop Ripping",
    description: "Open 25 packs total.",
    period: "season",
    type: "OPEN_PACKS_ANY",
    category: "Pack Grinder",
    seasonCode: SEASON_CODE,
    sortOrder: 11,
    isRepeatable: false,
    targetValue: 25,
    rewardType: "pack",
    rewardValue: "starter",
  },
  {
    code: "PACK_GRINDER_03",
    name: "Pack Addict",
    description: "Open 50 packs total.",
    period: "season",
    type: "OPEN_PACKS_ANY",
    category: "Pack Grinder",
    seasonCode: SEASON_CODE,
    sortOrder: 12,
    isRepeatable: false,
    targetValue: 50,
    rewardType: "pack",
    rewardValue: "silver",
  },
  {
    code: "PACK_GRINDER_04",
    name: "Mega Ripper",
    description: "Open 100 packs total.",
    period: "season",
    type: "OPEN_PACKS_ANY",
    category: "Pack Grinder",
    seasonCode: SEASON_CODE,
    sortOrder: 13,
    isRepeatable: false,
    targetValue: 100,
    rewardType: "pack",
    rewardValue: "gold",
  },

  // Collector Path
  {
    code: "COLLECTOR_01",
    name: "Mini Monster Squad",
    description: "Own 20 monsters in your collection.",
    period: "season",
    type: "OWN_MONSTERS_TOTAL",
    category: "Collector",
    seasonCode: SEASON_CODE,
    sortOrder: 20,
    isRepeatable: false,
    targetValue: 20,
    rewardType: "coins",
    rewardValue: "400",
  },
  {
    code: "COLLECTOR_02",
    name: "Growing Horde",
    description: "Own 50 monsters in your collection.",
    period: "season",
    type: "OWN_MONSTERS_TOTAL",
    category: "Collector",
    seasonCode: SEASON_CODE,
    sortOrder: 21,
    isRepeatable: false,
    targetValue: 50,
    rewardType: "pack",
    rewardValue: "starter",
  },
  {
    code: "COLLECTOR_03",
    name: "Rare Sightings",
    description: "Own 10 monsters of Rare rarity or better.",
    period: "season",
    type: "OWN_MONSTERS_RARE_OR_BETTER",
    category: "Collector",
    seasonCode: SEASON_CODE,
    sortOrder: 22,
    isRepeatable: false,
    targetValue: 10,
    rewardType: "coins",
    rewardValue: "800",
  },
  {
    code: "COLLECTOR_04",
    name: "Epic Collection",
    description: "Own 5 monsters of Epic rarity or better.",
    period: "season",
    type: "OWN_MONSTERS_RARE_OR_BETTER",
    category: "Collector",
    seasonCode: SEASON_CODE,
    sortOrder: 23,
    isRepeatable: false,
    targetValue: 5,
    rewardType: "pack",
    rewardValue: "silver",
  },
  {
    code: "COLLECTOR_05",
    name: "Legendary Keeper",
    description: "Own 1 Legendary monster.",
    period: "season",
    type: "OWN_MONSTERS_RARE_OR_BETTER",
    category: "Collector",
    seasonCode: SEASON_CODE,
    sortOrder: 24,
    isRepeatable: false,
    targetValue: 1,
    rewardType: "pack",
    rewardValue: "gold",
  },

  // Fantasy Path
  {
    code: "FANTASY_01",
    name: "Weekly Warrior",
    description: "Submit fantasy squads in 3 different gameweeks.",
    period: "season",
    type: "SUBMIT_FANTASY_SQUAD",
    category: "Fantasy",
    seasonCode: SEASON_CODE,
    sortOrder: 30,
    isRepeatable: false,
    targetValue: 3,
    rewardType: "coins",
    rewardValue: "500",
  },
  {
    code: "FANTASY_02",
    name: "Fantasy Regular",
    description: "Submit fantasy squads in 8 different gameweeks.",
    period: "season",
    type: "SUBMIT_FANTASY_SQUAD",
    category: "Fantasy",
    seasonCode: SEASON_CODE,
    sortOrder: 31,
    isRepeatable: false,
    targetValue: 8,
    rewardType: "pack",
    rewardValue: "starter",
  },
  {
    code: "FANTASY_03",
    name: "Points on the Board",
    description: "Earn 500 total fantasy points.",
    period: "season",
    type: "EARN_FANTASY_POINTS",
    category: "Fantasy",
    seasonCode: SEASON_CODE,
    sortOrder: 32,
    isRepeatable: false,
    targetValue: 500,
    rewardType: "coins",
    rewardValue: "800",
  },
  {
    code: "FANTASY_04",
    name: "Fantasy Grinder",
    description: "Earn 1500 total fantasy points.",
    period: "season",
    type: "EARN_FANTASY_POINTS",
    category: "Fantasy",
    seasonCode: SEASON_CODE,
    sortOrder: 33,
    isRepeatable: false,
    targetValue: 1500,
    rewardType: "pack",
    rewardValue: "silver",
  },

  // Arena Path
  {
    code: "ARENA_01",
    name: "First Blood",
    description: "Win 1 battle.",
    period: "season",
    type: "WIN_BATTLES",
    category: "Arena",
    seasonCode: SEASON_CODE,
    sortOrder: 40,
    isRepeatable: false,
    targetValue: 1,
    rewardType: "coins",
    rewardValue: "400",
  },
  {
    code: "ARENA_02",
    name: "Regular Fighter",
    description: "Play 20 battles.",
    period: "season",
    type: "PLAY_BATTLES",
    category: "Arena",
    seasonCode: SEASON_CODE,
    sortOrder: 41,
    isRepeatable: false,
    targetValue: 20,
    rewardType: "pack",
    rewardValue: "starter",
  },
  {
    code: "ARENA_03",
    name: "Monster Duelist",
    description: "Win 10 battles.",
    period: "season",
    type: "WIN_BATTLES",
    category: "Arena",
    seasonCode: SEASON_CODE,
    sortOrder: 42,
    isRepeatable: false,
    targetValue: 10,
    rewardType: "pack",
    rewardValue: "silver",
  },
  {
    code: "ARENA_04",
    name: "Arena Champion",
    description: "Win 30 battles.",
    period: "season",
    type: "WIN_BATTLES",
    category: "Arena",
    seasonCode: SEASON_CODE,
    sortOrder: 43,
    isRepeatable: false,
    targetValue: 30,
    rewardType: "pack",
    rewardValue: "gold",
  },

  // Evolution Path
  {
    code: "EVOLUTION_01",
    name: "First Evolution",
    description: "Evolve a monster once.",
    period: "season",
    type: "EVOLVE_MONSTERS",
    category: "Evolution",
    seasonCode: SEASON_CODE,
    sortOrder: 50,
    isRepeatable: false,
    targetValue: 1,
    rewardType: "coins",
    rewardValue: "500",
  },
  {
    code: "EVOLUTION_02",
    name: "Team Upgrade",
    description: "Evolve 5 monsters.",
    period: "season",
    type: "EVOLVE_MONSTERS",
    category: "Evolution",
    seasonCode: SEASON_CODE,
    sortOrder: 51,
    isRepeatable: false,
    targetValue: 5,
    rewardType: "pack",
    rewardValue: "starter",
  },
  {
    code: "EVOLUTION_03",
    name: "Master Breeder",
    description: "Evolve 15 monsters.",
    period: "season",
    type: "EVOLVE_MONSTERS",
    category: "Evolution",
    seasonCode: SEASON_CODE,
    sortOrder: 52,
    isRepeatable: false,
    targetValue: 15,
    rewardType: "pack",
    rewardValue: "silver",
  },

  // Marketplace Path
  {
    code: "MARKET_01",
    name: "First Purchase",
    description: "Buy 1 monster from the marketplace.",
    period: "season",
    type: "USE_MARKETPLACE_BUY",
    category: "Marketplace",
    seasonCode: SEASON_CODE,
    sortOrder: 60,
    isRepeatable: false,
    targetValue: 1,
    rewardType: "coins",
    rewardValue: "500",
  },
  {
    code: "MARKET_02",
    name: "Trader",
    description: "Sell 3 monsters on the marketplace.",
    period: "season",
    type: "USE_MARKETPLACE_SELL",
    category: "Marketplace",
    seasonCode: SEASON_CODE,
    sortOrder: 61,
    isRepeatable: false,
    targetValue: 3,
    rewardType: "pack",
    rewardValue: "starter",
  },
  {
    code: "MARKET_03",
    name: "Market Mogul",
    description: "Complete 10 marketplace transactions (buy or sell).",
    period: "season",
    // In the engine we treat both buy and sell as progress for this type.
    type: "USE_MARKETPLACE_BUY",
    category: "Marketplace",
    seasonCode: SEASON_CODE,
    sortOrder: 62,
    isRepeatable: false,
    targetValue: 10,
    rewardType: "pack",
    rewardValue: "silver",
  },
];

export const season1ObjectiveSets: SeasonObjectiveSetConfig[] = [
  {
    code: "SET_GETTING_STARTED",
    title: "Getting Started Path",
    description: "Complete all Getting Started objectives.",
    seasonCode: SEASON_CODE,
    sortOrder: 1,
    rewardType: "pack",
    rewardValue: "silver",
    objectiveCodes: ["GET_STARTED_01", "GET_STARTED_02", "GET_STARTED_03", "GET_STARTED_04"],
  },
  {
    code: "SET_PACK_GRINDER",
    title: "Pack Grinder Path",
    description: "Complete all Pack Grinder objectives.",
    seasonCode: SEASON_CODE,
    sortOrder: 2,
    rewardType: "pack",
    rewardValue: "gold",
    objectiveCodes: ["PACK_GRINDER_01", "PACK_GRINDER_02", "PACK_GRINDER_03", "PACK_GRINDER_04"],
  },
  {
    code: "SET_COLLECTOR",
    title: "Collector Path",
    description: "Complete all Collector objectives.",
    seasonCode: SEASON_CODE,
    sortOrder: 3,
    rewardType: "pack",
    rewardValue: "gold",
    objectiveCodes: [
      "COLLECTOR_01",
      "COLLECTOR_02",
      "COLLECTOR_03",
      "COLLECTOR_04",
      "COLLECTOR_05",
    ],
  },
  {
    code: "SET_FANTASY",
    title: "Fantasy Path",
    description: "Complete all Fantasy objectives.",
    seasonCode: SEASON_CODE,
    sortOrder: 4,
    rewardType: "pack",
    rewardValue: "silver",
    objectiveCodes: ["FANTASY_01", "FANTASY_02", "FANTASY_03", "FANTASY_04"],
  },
  {
    code: "SET_ARENA",
    title: "Arena Warrior Path",
    description: "Complete all Arena objectives.",
    seasonCode: SEASON_CODE,
    sortOrder: 5,
    rewardType: "pack",
    rewardValue: "gold",
    objectiveCodes: ["ARENA_01", "ARENA_02", "ARENA_03", "ARENA_04"],
  },
  {
    code: "SET_EVOLUTION",
    title: "Evolution Master Path",
    description: "Complete all Evolution objectives.",
    seasonCode: SEASON_CODE,
    sortOrder: 6,
    rewardType: "pack",
    rewardValue: "silver",
    objectiveCodes: ["EVOLUTION_01", "EVOLUTION_02", "EVOLUTION_03"],
  },
  {
    code: "SET_MARKET",
    title: "Market Mogul Path",
    description: "Complete all Marketplace objectives.",
    seasonCode: SEASON_CODE,
    sortOrder: 7,
    rewardType: "pack",
    rewardValue: "silver",
    objectiveCodes: ["MARKET_01", "MARKET_02", "MARKET_03"],
  },
];
